export const newsResources = [
  {
    folderId: 0,
    folderName: 'Q News',
    links: [
      {
        linkId: 0,
        linkUrl: 'https://qsciences.com',
        linkTitle: 'Featured Q News',
        linkDescription: `This is featured story text. We need to determine how many lines if test are going to be displayed before we cut it off and force the user to click the tile to send them to an outside source to further consume the wonderful content that the communications team has ready for them. But this is more text to help us see where the cut off is going to be.`,
        imageUrl:
          'https://firebasestorage.googleapis.com/v0/b/q-connect-pro-staging.appspot.com/o/resources%2Fbanners%2FEventsBanner_355x176.jpg?alt=media&token=72e6d8fa-4406-43cc-9198-80f76eb0c880',
        isViewedByAssociate: false,
        dateStart: new Date(Date.UTC(2012, 3, 21, 3, 0, 0)),
      },
      {
        linkId: 1,
        linkUrl: 'https://qsciences.com',
        linkTitle: 'Random title',
        linkDescription: `This is featured story text. We need to determine how many lines if test are going to be displayed before we cut it off and force the user to click the tile to send them to an outside source to further consume the wonderful content that the communications team has ready for them. But this is more text to help us see where the cut off is going to be.`,
        isViewedByAssociate: false,
        dateStart: new Date(Date.UTC(2012, 3, 21, 3, 0, 0)),
      },
      {
        linkId: 2,
        linkUrl: 'https://qsciences.com',
        linkTitle: 'Another random title',
        linkDescription: `This is featured story text. We need to determine how many lines if test are going to be displayed before we cut it off and force the user to click the tile to send them to an outside source to further consume the wonderful content that the communications team has ready for them. But this is more text to help us see where the cut off is going to be.`,
        imageUrl: '',
        isViewedByAssociate: true,
        dateStart: new Date(Date.UTC(2012, 3, 21, 3, 0, 0)),
      },
      {
        linkId: 3,
        linkUrl: 'https://qsciences.com',
        linkTitle: 'Final title that is random',
        linkDescription: `This is featured story text. We need to determine how many lines if test are going to be displayed before we cut it off and force the user to click the tile to send them to an outside source to further consume the wonderful content that the communications team has ready for them. But this is more text to help us see where the cut off is going to be.`,
        imageUrl: '',
        isViewedByAssociate: true,
        dateStart: new Date(Date.UTC(2012, 3, 21, 3, 0, 0)),
      },
    ],
  },
  {
    folderId: 1,
    folderName: 'Blog',
    links: [
      {
        linkId: 10,
        linkUrl: 'https://qsciences.com',
        linkTitle: 'Featured Blog',
        linkDescription: `This is featured story text. We need to determine how many lines if test are going to be displayed before we cut it off and force the user to click the tile to send them to an outside source to further consume the wonderful content that the communications team has ready for them. But this is more text to help us see where the cut off is going to be.`,
        imageUrl:
          'https://firebasestorage.googleapis.com/v0/b/q-connect-pro-staging.appspot.com/o/resources%2Fbanners%2FCompPlanBanner_355x176.jpg?alt=media&token=ed482437-f2cb-43bc-8ee0-8bbb73af991d',
        isViewedByAssociate: false,
        dateStart: new Date(Date.UTC(2012, 3, 21, 3, 0, 0)),
      },
      {
        linkId: 11,
        linkUrl: 'https://qsciences.com',
        linkTitle: 'Random Blog title',
        linkDescription: `This is featured story text. We need to determine how many lines if test are going to be displayed before we cut it off and force the user to click the tile to send them to an outside source to further consume the wonderful content that the communications team has ready for them. But this is more text to help us see where the cut off is going to be.`,
        imageUrl:
          'https://firebasestorage.googleapis.com/v0/b/q-connect-pro-staging.appspot.com/o/resources%2Fbanners%2FEventsBanner_355x176.jpg?alt=media&token=72e6d8fa-4406-43cc-9198-80f76eb0c880',
        isViewedByAssociate: false,
        dateStart: new Date(Date.UTC(2012, 3, 21, 3, 0, 0)),
      },
      {
        linkId: 12,
        linkUrl: 'https://qsciences.com',
        linkTitle: 'Another random title',
        linkDescription: `This is featured story text. We need to determine how many lines if test are going to be displayed before we cut it off and force the user to click the tile to send them to an outside source to further consume the wonderful content that the communications team has ready for them. But this is more text to help us see where the cut off is going to be.`,
        imageUrl: '',
        isViewedByAssociate: true,
        dateStart: new Date(Date.UTC(2012, 3, 21, 3, 0, 0)),
      },
      {
        linkId: 13,
        linkUrl: 'https://qsciences.com',
        linkTitle: 'Final title that is random',
        linkDescription: `This is featured story text. We need to determine how many lines if test are going to be displayed before we cut it off and force the user to click the tile to send them to an outside source to further consume the wonderful content that the communications team has ready for them. But this is more text to help us see where the cut off is going to be.`,
        imageUrl: '',
        isViewedByAssociate: true,
        dateStart: new Date(Date.UTC(2012, 3, 21, 3, 0, 0)),
      },
    ],
  },
  {
    folderId: 2,
    folderName: 'In the Queue',
    links: [
      {
        linkId: 20,
        linkUrl: 'https://qsciences.com',
        linkTitle: 'Featured Event',
        linkDescription: `This is story text. We need to determine how many lines if test are going to be displayed before we cut it off and force the user to click the tile to send them to an outside source to further consume the wonderful content that the communications team has ready for them. But this is more text to help us see where the cut off is going to be.`,
        imageUrl:
          'https://firebasestorage.googleapis.com/v0/b/q-connect-pro-staging.appspot.com/o/resources%2Fbanners%2FCompPlanBanner_355x176.jpg?alt=media&token=ed482437-f2cb-43bc-8ee0-8bbb73af991d',
        isViewedByAssociate: false,
        dateStart: new Date(Date.UTC(2012, 3, 21, 3, 0, 0)),
      },
      {
        linkId: 21,
        linkUrl: 'https://qsciences.com',
        linkTitle: 'Random title',
        linkDescription: `This is featured story text. We need to determine how many lines if test are going to be displayed before we cut it off and force the user to click the tile to send them to an outside source to further consume the wonderful content that the communications team has ready for them. But this is more text to help us see where the cut off is going to be.`,
        imageUrl:
          'https://firebasestorage.googleapis.com/v0/b/q-connect-pro-staging.appspot.com/o/resources%2Fbanners%2FEventsBanner_355x176.jpg?alt=media&token=72e6d8fa-4406-43cc-9198-80f76eb0c880',
        isViewedByAssociate: false,
        dateStart: new Date(Date.UTC(2012, 3, 21, 3, 0, 0)),
      },
      {
        linkId: 22,
        linkUrl: 'https://qsciences.com',
        linkTitle: 'Another random title',
        linkDescription: `This is featured story text. We need to determine how many lines if test are going to be displayed before we cut it off and force the user to click the tile to send them to an outside source to further consume the wonderful content that the communications team has ready for them. But this is more text to help us see where the cut off is going to be.`,
        imageUrl: '',
        isViewedByAssociate: true,
        dateStart: new Date(Date.UTC(2012, 3, 21, 3, 0, 0)),
      },
      {
        linkId: 23,
        linkUrl: 'https://qsciences.com',
        linkTitle: 'Final title that is random',
        linkDescription: `This is featured story text. We need to determine how many lines if test are going to be displayed before we cut it off and force the user to click the tile to send them to an outside source to further consume the wonderful content that the communications team has ready for them. But this is more text to help us see where the cut off is going to be.`,
        imageUrl: '',
        isViewedByAssociate: true,
        dateStart: new Date(Date.UTC(2012, 3, 21, 3, 0, 0)),
      },
    ],
  },
];
