export const mockNews = {
  qnews: {
    featured: {
      url:
        'https://firebasestorage.googleapis.com/v0/b/q-connect-pro-staging.appspot.com/o/resources%2Fbanners%2FEventsBanner_355x176.jpg?alt=media&token=72e6d8fa-4406-43cc-9198-80f76eb0c880',
      title: 'Featured Story Headline',
      body: `This is featheured story text. We nned to determine how many lines if test are going to be displayed before we cut it off and force the user to click the tile to send them to an outside source to further consume the wonderful content that the communications team has ready for them. But this is more text to help us see where the cut off is going to be.`,
    },
    storyList: [
      {
        id: 0,
        url: '',
        title: 'Random Title',
        body: `This is a news story that the Q NEWS team published for ambassadors to see articles that are relevant to their businesses`,
        isNew: true,
        // date: new Date(Date.UTC(2021, 12, 2, 3, 0, 0)),
      },
      {
        id: 1,
        url: 'https://qsciences.com',
        title: 'Another Title',
        body: `This is a news story that the Q NEWS team published and this one is a little bit longer than the previous one so we can see how large the card gets when it is expanded so that is neat don't you think?`,
        isNew: true,
        date: new Date(Date.UTC(2012, 1, 20, 3, 0, 0)),
      },
      {
        id: 2,
        url: 'https://qsciences.com',
        title: 'Another Random Title',
        body: `This is a really long news story that the Q NEWS communications team is going to add so that the ambassadors can find cool content inside of the app. They even might add them in different languages and stuff like that. s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that`,
        isNew: false,
        date: new Date(Date.UTC(2012, 3, 5, 3, 0, 0)),
      },
      {
        id: 3,
        url: 'https://qsciences.com',
        title: 'Random Title Again',
        body: `This is a really long news story that the Q NEWS communications team is going to add so that the ambassadors can find cool content inside of the app. They even might add them in different languages and stuff like that. s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to `,
        isNew: false,
        date: new Date(Date.UTC(2012, 2, 19, 3, 0, 0)),
      },
    ],
  },
  blog: {
    storyList: [
      {
        id: 0,
        url: 'https://qsciences.com',
        title: 'Random Blog Title',
        body: `This is a really long news story that the Q NEWS communications team is going to add so that the ambassadors can find cool content inside of the app. They even might add them in different languages and stuff like that. s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to `,
        isNew: true,
        date: new Date(Date.UTC(2012, 1, 14, 3, 0, 0)),
      },
      {
        id: 1,
        url: 'https://qsciences.com',
        title: 'Another Blog Title',
        body: `This is a really long news story that the Q NEWS communications team is going to add so that the ambassadors can find cool content inside of the app. They even might add them in different languages and stuff like that. s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to `,
        isNew: true,
        date: new Date(Date.UTC(2012, 5, 27, 3, 0, 0)),
      },
      {
        id: 2,
        url: 'https://qsciences.com',
        title: 'Random Title',
        body: `This is a really long news story that the Q NEWS communications team is going to add so that the ambassadors can find cool content inside of the app. They even might add them in different languages and stuff like that. s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to `,
        isNew: false,
        date: new Date(Date.UTC(2012, 8, 2, 3, 0, 0)),
      },
      {
        id: 3,
        url: 'https://qsciences.com',
        title: 'Blog Title Again',
        body: `This is a really long news story that the Q NEWS communications team is going to add so that the ambassadors can find cool content inside of the app. They even might add them in different languages and stuff like that. s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to `,
        isNew: false,
        date: new Date(Date.UTC(2012, 4, 6, 3, 0, 0)),
      },
    ],
  },
  events: {
    storyList: [
      {
        id: 0,
        url: 'https://qsciences.com',
        title: 'Event Title',
        body: `This is a really long news story that the Q NEWS communications team is going to add so that the ambassadors can find cool content inside of the app. They even might add them in different languages and stuff like that. s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to `,
        isNew: true,
      },
      {
        id: 1,
        url: 'https://qsciences.com',
        title: 'Another Event Title',
        body: `This is a really long news story that the Q NEWS communications team is going to add so that the ambassadors can find cool content inside of the app. They even might add them in different languages and stuff like that. s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to `,
        isNew: true,
        date: new Date(Date.UTC(2012, 4, 3, 3, 0, 0)),
      },
      {
        id: 2,
        url: 'https://qsciences.com',
        title: 'Random Title',
        body: `This is a really long news story that the Q NEWS communications team is going to add so that the ambassadors can find cool content inside of the app. They even might add them in different languages and stuff like that. s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to `,
        isNew: false,
      },
      {
        id: 3,
        url: 'https://qsciences.com',
        title: 'Event Title Again',
        body: `This is a really long news story that the Q NEWS communications team is going to add so that the ambassadors can find cool content inside of the app. They even might add them in different languages and stuff like that. s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to s is a really long news story that the Q NEWS communications team is going to `,
        isNew: false,
        date: new Date(Date.UTC(2012, 3, 21, 3, 0, 0)),
      },
    ],
  },
};
