import {
  primaryWhite,
  secondaryWhite,
  disabledWhite,
  black,
  nero,
  darkgray,
  gray,
  lightgray,
  blue,
  red,
  transparentGray,
  cobaltBlue,
  highlightWhite,
  tealAccent,
  tealAccentDark,
  tealAccentLight,
  orangeAccent,
  orangeAccentDark,
  orangeAccentLight,
  yellowAccent,
  yellowAccentDark,
  yellowAccentLight,
  blueAccent,
  blueAccentDark,
  blueAccentLight,
  purpleAccent,
  purpleAccentDark,
  purpleAccentLight,
  caramel,
  violet,
  darkRed,
  warningYellow,
} from './colors';
import { dropShadow, lightUpperDropShadow } from './constants';

// source for themes with styled components: https://styled-components.com/docs/advanced#theming
export const lightTheme = {
  primaryTextColor: black,
  secondaryTextColor: gray,
  disabledTextColor: gray,
  selectedCardHighlight: black,
  placeholderTextColor: disabledWhite,
  backgroundColor: primaryWhite,
  activeBackground: darkgray,
  inactiveBackground: lightgray,
  activeTint: primaryWhite,
  inactiveTint: blue,
  primaryButtonBackgroundColor: blue,
  disabledBackgroundColor: lightgray,
  highlight: blue,
  error: red,
  headerBackgroundColor: blue,
  subheaderBackgroundColor: darkgray,
  tertiarySelectedTextColor: blue,
  tertiaryDisabledTextColor: blue,
  tertiarySelectedBackgroundColor: primaryWhite,
  tertiaryDisabledBackgroundColor: blue,
  tertiarySelectedBorderColor: primaryWhite,
  tertiaryDisabledBorderColor: secondaryWhite,
  primaryOpacity: 0.83,
  secondaryOpacity: 0.6,
  disabledOpacity: 0.5,
  modalBackgroundColor: transparentGray,
  activeSwitchBackground: '#006699',
  inactiveSwitchBackground: darkgray,
  activeSwitchThumb: '#8DB600',
  inactiveSwitchThumb: gray,
  sideMenuBackground: nero,
  topButtonBarBackground: nero,
  sliderTrackColor: darkgray,
  sliderThumbColor: blue,
  cardBackgroundColor: darkgray,
  favoriteFillColor: cobaltBlue,
  statusBar: 'dark',
  autoshipPie1: tealAccentDark,
  autoshipPie2: tealAccentLight,
  autoshipPie3: tealAccent,
  ambassadorEnrollmentsPie1: orangeAccentDark,
  ambassadorEnrollmentsPie2: orangeAccentLight,
  ambassadorEnrollmentsPie3: orangeAccent,
  pcEnrollmentsPie1: yellowAccentDark,
  pcEnrollmentsPie2: yellowAccentLight,
  pcEnrollmentsPie3: yellowAccent,
  eventTicketsPie1: blueAccentDark,
  eventTicketsPie2: blueAccentLight,
  eventTicketsPie3: blueAccent,
  payoutsPie1: purpleAccentDark,
  payoutsPie2: purpleAccentLight,
  payoutsPie3: purpleAccent,
  customerAvatarAccent: caramel,
  retailAvatarAccent: violet,
  alertAvatarAccent: darkRed,
  warningAvatarAccent: warningYellow,
  donut1primaryColor: tealAccent,
  donut1secondaryColor: tealAccentLight,
  donut2primaryColor: purpleAccent,
  donut2secondaryColor: purpleAccentLight,
  donut3primaryColor: orangeAccent,
  donut3secondaryColor: orangeAccentLight,
  dropShadow: dropShadow,
  bubbleShadow: lightUpperDropShadow,
};

export const darkTheme = {
  primaryTextColor: primaryWhite,
  secondaryTextColor: secondaryWhite,
  disabledTextColor: gray,
  selectedCardHighlight: highlightWhite,
  placeholderTextColor: disabledWhite,
  backgroundColor: black,
  activeBackground: nero,
  inactiveBackground: nero,
  activeTint: primaryWhite,
  inactiveTint: disabledWhite,
  primaryButtonBackgroundColor: blue,
  disabledBackgroundColor: lightgray,
  highlight: blue,
  error: red,
  headerBackgroundColor: black,
  subheaderBackgroundColor: darkgray,
  tertiarySelectedTextColor: primaryWhite,
  tertiaryDisabledTextColor: primaryWhite,
  tertiarySelectedBackgroundColor: 'transparent',
  tertiaryDisabledBackgroundColor: 'transparent',
  tertiarySelectedBorderColor: primaryWhite,
  tertiaryDisabledBorderColor: secondaryWhite,
  primaryOpacity: 0.83,
  secondaryOpacity: 0.6,
  disabledOpacity: 0.5,
  modalBackgroundColor: transparentGray,
  activeSwitchBackground: 'rgba(0,102,153,0.75)',
  inactiveSwitchBackground: darkgray,
  activeSwitchThumb: blue,
  inactiveSwitchThumb: gray,
  sideMenuBackground: nero,
  topButtonBarBackground: nero,
  sliderTrackColor: darkgray,
  sliderThumbColor: primaryWhite,
  cardBackgroundColor: darkgray,
  favoriteFillColor: cobaltBlue,
  statusBar: 'light',
  autoshipPie1: tealAccentDark,
  autoshipPie2: tealAccentLight,
  autoshipPie3: tealAccent,
  ambassadorEnrollmentsPie1: orangeAccentDark,
  ambassadorEnrollmentsPie2: orangeAccentLight,
  ambassadorEnrollmentsPie3: orangeAccent,
  pcEnrollmentsPie1: yellowAccentDark,
  pcEnrollmentsPie2: yellowAccentLight,
  pcEnrollmentsPie3: yellowAccent,
  eventTicketsPie1: blueAccentDark,
  eventTicketsPie2: blueAccentLight,
  eventTicketsPie3: blueAccent,
  payoutsPie1: purpleAccentDark,
  payoutsPie2: purpleAccentLight,
  payoutsPie3: purpleAccent,
  customerAvatarAccent: caramel,
  retailAvatarAccent: violet,
  alertAvatarAccent: darkRed,
  warningAvatarAccent: warningYellow,
  donut1primaryColor: tealAccent,
  donut1secondaryColor: tealAccentLight,
  donut2primaryColor: purpleAccent,
  donut2secondaryColor: purpleAccentLight,
  donut3primaryColor: orangeAccent,
  donut3secondaryColor: orangeAccentLight,
  dropShadow: dropShadow,
  bubbleShadow: lightUpperDropShadow,
};
