export default [
  {
    sentLinkId: 0,
    title: 'Jane Bond',
    description: 'Viewed Comp Plan.pdf',
    isSaved: false,
    dateSent: '',
  },
  {
    sentLinkId: 1,
    title: 'James Bond',
    description: 'Viewed Comp Plan.pdf',
    isSaved: false,
    dateSent: '',
  },
  {
    sentLinkId: 2,
    title: 'James Bobby',
    description: 'Viewed Comp Plan.pdf',
    isSaved: false,
    dateSent: '',
  },
  {
    sentLinkId: 3,
    title: 'Hilary Bond',
    description: 'Viewed Comp Plan.pdf',
    isSaved: false,
    dateSent: '',
  },
  {
    sentLinkId: 4,
    title: 'James Johnston',
    description: 'Viewed Comp Plan.pdf',
    isSaved: false,
    dateSent: '',
  },
  {
    sentLinkId: 5,
    title: 'Veronica Smith',
    description: 'Viewed Comp Plan.pdf',
    isSaved: false,
    dateSent: '',
  },
  {
    sentLinkId: 6,
    title: 'Nancy Gonzales',
    description: 'Viewed Comp Plan.pdf',
    isSaved: false,
    dateSent: '',
  },
  {
    sentLinkId: 7,
    title: 'Jim Bean',
    description: 'Viewed Comp Plan.pdf',
    isSaved: false,
    dateSent: '',
  },
  {
    sentLinkId: 8,
    title: 'Barbara Grant',
    description: 'Viewed Comp Plan.pdf',
    isSaved: false,
    dateSent: '',
  },
];
