export const mockChildTree = [
  {
    associate: {
      associateId: 75197,
      legacyAssociateId: 272398,
      firstName: 'Karlie',
      lastName: 'Hodgen',
      profileUrl: null,
      associateType: 'AMBASSADOR',
      associateStatus: 'TERMINATED',
    },
    rank: {
      rankId: 1,
      rankName: 'Ambassador',
    },
    pv: 0,
    qoV: 0,
    pa: 0,
  },
  {
    associate: {
      associateId: 202602,
      legacyAssociateId: 742546,
      firstName: 'Matthew',
      lastName: 'Adams',
      profileUrl: null,
      associateType: 'AMBASSADOR',
      associateStatus: 'ACTIVE',
    },
    rank: {
      rankId: 1,
      rankName: 'Ambassador',
    },
    pv: 0,
    qoV: 0,
    pa: 0,
  },
  {
    associate: {
      associateId: 152996,
      legacyAssociateId: 622003,
      firstName: 'Angela',
      lastName: 'Mourlam',
      profileUrl: null,
      associateType: 'AMBASSADOR',
      associateStatus: 'SUSPENDED',
    },
    rank: {
      rankId: 1,
      rankName: 'Ambassador',
    },
    pv: 0,
    qoV: 0,
    pa: 0,
  },
  {
    associate: {
      associateId: 85981,
      legacyAssociateId: 319342,
      firstName: 'Kelsey',
      lastName: 'Bowman',
      profileUrl: null,
      associateType: 'PREFERRED',
      associateStatus: 'TERMINATED',
    },
    rank: {
      rankId: 1,
      rankName: 'Ambassador',
    },
    pv: 0,
    qoV: 0,
    pa: 0,
  },
  {
    associate: {
      associateId: 86111,
      legacyAssociateId: 319822,
      firstName: 'Misty',
      lastName: 'Rivera',
      profileUrl: null,
      associateType: 'RETAIL',
      associateStatus: 'TERMINATED',
    },
    rank: {
      rankId: 1,
      rankName: 'Ambassador',
    },
    pv: 0,
    qoV: 0,
    pa: 0,
  },
  {
    associate: {
      associateId: 86478,
      legacyAssociateId: 321223,
      firstName: 'Brooke',
      lastName: 'Mutapcic',
      profileUrl: null,
      associateType: 'PREFERRED',
      associateStatus: 'TERMINATED',
    },
    rank: {
      rankId: 1,
      rankName: 'Ambassador',
    },
    pv: 0,
    qoV: 0,
    pa: 0,
  },
  {
    associate: {
      associateId: 93133,
      legacyAssociateId: 353092,
      firstName: 'Michelle',
      lastName: 'Bartusek',
      profileUrl: null,
      associateType: 'PREFERRED',
      associateStatus: 'TERMINATED',
    },
    rank: {
      rankId: 1,
      rankName: 'Ambassador',
    },
    pv: 0,
    qoV: 0,
    pa: 0,
  },
];

// TWO LEVELS DEEP
export const mockTreeTwoLevelsDeep = [
  {
    associate: {
      associateId: 74951,
      legacyAssociateId: 271471,
      firstName: 'Dustin',
      lastName: 'Free',
      profileUrl: null,
      associateType: 'AMBASSADOR',
      associateStatus: 'TERMINATED',
    },
    rank: {
      rankId: 1,
      rankName: 'Ambassador',
    },
    pv: 0,
    qoV: 0,
    pa: 0,
    childTreeNodes: [
      {
        associate: {
          associateId: 75251,
          legacyAssociateId: 272614,
          firstName: 'Danielle',
          lastName: 'Glymph',
          profileUrl: null,
          associateType: 'AMBASSADOR',
          associateStatus: 'TERMINATED',
        },
        rank: {
          rankId: 1,
          rankName: 'Ambassador',
        },
        pv: 0,
        qoV: 0,
        pa: 0,
      },
      {
        associate: {
          associateId: 75400,
          legacyAssociateId: 273181,
          firstName: 'Mary Anne',
          lastName: 'Lewis',
          profileUrl: null,
          associateType: 'AMBASSADOR',
          associateStatus: 'DOCU_SIGN_HOLD',
        },
        rank: {
          rankId: 1,
          rankName: 'Ambassador',
        },
        pv: 0,
        qoV: 1600.0,
        pa: 0,
      },
    ],
  },
  {
    associate: {
      associateId: 75101,
      legacyAssociateId: 272008,
      firstName: 'DENISE',
      lastName: 'POTTROFF',
      profileUrl: null,
      associateType: 'PREFERRED',
      associateStatus: 'TERMINATED',
    },
    rank: {
      rankId: 1,
      rankName: 'Ambassador',
    },
    pv: 0,
    qoV: 0,
    pa: 0,
    childTreeNodes: [],
  },
  {
    associate: {
      associateId: 75197,
      legacyAssociateId: 272398,
      firstName: 'Karlie',
      lastName: 'Hodgen',
      profileUrl: null,
      associateType: 'AMBASSADOR',
      associateStatus: 'TERMINATED',
    },
    rank: {
      rankId: 1,
      rankName: 'Ambassador',
    },
    pv: 0,
    qoV: 0,
    pa: 0,
    childTreeNodes: [
      {
        associate: {
          associateId: 75992,
          legacyAssociateId: 275641,
          firstName: 'Tim',
          lastName: 'Foster',
          profileUrl: null,
          associateType: 'PREFERRED',
          associateStatus: 'TERMINATED',
        },
        rank: {
          rankId: 1,
          rankName: 'Ambassador',
        },
        pv: 0,
        qoV: 0,
        pa: 0,
      },
      {
        associate: {
          associateId: 81016,
          legacyAssociateId: 298012,
          firstName: 'Hateesha',
          lastName: 'Brown',
          profileUrl: null,
          associateType: 'AMBASSADOR',
          associateStatus: 'TERMINATED',
        },
        rank: {
          rankId: 1,
          rankName: 'Ambassador',
        },
        pv: 0,
        qoV: 0,
        pa: 0,
      },
      {
        associate: {
          associateId: 83203,
          legacyAssociateId: 307258,
          firstName: 'Cheryl',
          lastName: 'Pelto',
          profileUrl: null,
          associateType: 'PREFERRED',
          associateStatus: 'TERMINATED',
        },
        rank: {
          rankId: 1,
          rankName: 'Ambassador',
        },
        pv: 0,
        qoV: 0,
        pa: 0,
      },
      {
        associate: {
          associateId: 86179,
          legacyAssociateId: 320095,
          firstName: 'Jeani K',
          lastName: 'Hodgen',
          profileUrl: null,
          associateType: 'PREFERRED',
          associateStatus: 'TERMINATED',
        },
        rank: {
          rankId: 1,
          rankName: 'Ambassador',
        },
        pv: 0,
        qoV: 0,
        pa: 0,
      },
      {
        associate: {
          associateId: 91206,
          legacyAssociateId: 343549,
          firstName: 'Jana',
          lastName: 'Lenssen',
          profileUrl: null,
          associateType: 'PREFERRED',
          associateStatus: 'TERMINATED',
        },
        rank: {
          rankId: 1,
          rankName: 'Ambassador',
        },
        pv: 0,
        qoV: 0,
        pa: 0,
      },
      {
        associate: {
          associateId: 92131,
          legacyAssociateId: 347839,
          firstName: 'Cyndi',
          lastName: 'Camp',
          profileUrl: null,
          associateType: 'PREFERRED',
          associateStatus: 'TERMINATED',
        },
        rank: {
          rankId: 1,
          rankName: 'Ambassador',
        },
        pv: 0,
        qoV: 0,
        pa: 0,
      },
      {
        associate: {
          associateId: 95066,
          legacyAssociateId: 361825,
          firstName: 'Korissa',
          lastName: 'Wentz',
          profileUrl: null,
          associateType: 'PREFERRED',
          associateStatus: 'TERMINATED',
        },
        rank: {
          rankId: 1,
          rankName: 'Ambassador',
        },
        pv: 0,
        qoV: 0,
        pa: 0,
      },
      {
        associate: {
          associateId: 95132,
          legacyAssociateId: 362173,
          firstName: 'Krysta',
          lastName: 'Bye',
          profileUrl: null,
          associateType: 'PREFERRED',
          associateStatus: 'TERMINATED',
        },
        rank: {
          rankId: 1,
          rankName: 'Ambassador',
        },
        pv: 0,
        qoV: 0,
        pa: 0,
      },
      {
        associate: {
          associateId: 96296,
          legacyAssociateId: 367828,
          firstName: 'Evie',
          lastName: 'Wilkinson',
          profileUrl: null,
          associateType: 'PREFERRED',
          associateStatus: 'TERMINATED',
        },
        rank: {
          rankId: 1,
          rankName: 'Ambassador',
        },
        pv: 0,
        qoV: 0,
        pa: 0,
      },
      {
        associate: {
          associateId: 100408,
          legacyAssociateId: 389308,
          firstName: 'Tania',
          lastName: 'Caldwell',
          profileUrl: null,
          associateType: 'RETAIL',
          associateStatus: 'TERMINATED',
        },
        rank: {
          rankId: 1,
          rankName: 'Ambassador',
        },
        pv: 0,
        qoV: 0,
        pa: 0,
      },
      {
        associate: {
          associateId: 104508,
          legacyAssociateId: 409360,
          firstName: 'xochil',
          lastName: 'silva',
          profileUrl: null,
          associateType: 'AMBASSADOR',
          associateStatus: 'SUSPENDED',
        },
        rank: {
          rankId: 1,
          rankName: 'Ambassador',
        },
        pv: 0,
        qoV: 0,
        pa: 0,
      },
      {
        associate: {
          associateId: 109852,
          legacyAssociateId: 433165,
          firstName: 'Karlie',
          lastName: 'Hodgen',
          profileUrl: null,
          associateType: 'PREFERRED',
          associateStatus: 'TERMINATED',
        },
        rank: {
          rankId: 1,
          rankName: 'Ambassador',
        },
        pv: 0,
        qoV: 0,
        pa: 0,
      },
    ],
  },
  {
    associate: {
      associateId: 75682,
      legacyAssociateId: 274360,
      firstName: 'matt',
      lastName: 'adams',
      profileUrl: null,
      associateType: 'PREFERRED',
      associateStatus: 'TERMINATED',
    },
    rank: {
      rankId: 1,
      rankName: 'Ambassador',
    },
    pv: 0,
    qoV: 0,
    pa: 0,
    childTreeNodes: [],
  },
  {
    associate: {
      associateId: 76804,
      legacyAssociateId: 278998,
      firstName: 'Lindsie',
      lastName: 'Anderson',
      profileUrl: null,
      associateType: 'PREFERRED',
      associateStatus: 'TERMINATED',
    },
    rank: {
      rankId: 1,
      rankName: 'Ambassador',
    },
    pv: 0,
    qoV: 0,
    pa: 0,
    childTreeNodes: [],
  },
  {
    associate: {
      associateId: 77619,
      legacyAssociateId: 282250,
      firstName: 'jamie',
      lastName: 'frost',
      profileUrl: null,
      associateType: 'PREFERRED',
      associateStatus: 'TERMINATED',
    },
    rank: {
      rankId: 1,
      rankName: 'Ambassador',
    },
    pv: 0,
    qoV: 0,
    pa: 0,
    childTreeNodes: [],
  },
  {
    associate: {
      associateId: 78146,
      legacyAssociateId: 284431,
      firstName: 'Leighanne',
      lastName: 'Formyduval',
      profileUrl: null,
      associateType: 'PREFERRED',
      associateStatus: 'TERMINATED',
    },
    rank: {
      rankId: 1,
      rankName: 'Ambassador',
    },
    pv: 0,
    qoV: 0,
    pa: 0,
    childTreeNodes: [],
  },
  {
    associate: {
      associateId: 80730,
      legacyAssociateId: 296797,
      firstName: 'Tasia',
      lastName: 'Brooks',
      profileUrl: null,
      associateType: 'AMBASSADOR',
      associateStatus: 'ACTIVE',
    },
    rank: {
      rankId: 1,
      rankName: 'Ambassador',
    },
    pv: 0,
    qoV: 0,
    pa: 0,
    childTreeNodes: [
      {
        associate: {
          associateId: 85981,
          legacyAssociateId: 319342,
          firstName: 'Kelsey',
          lastName: 'Bowman',
          profileUrl: null,
          associateType: 'PREFERRED',
          associateStatus: 'TERMINATED',
        },
        rank: {
          rankId: 1,
          rankName: 'Ambassador',
        },
        pv: 0,
        qoV: 0,
        pa: 0,
        childTreeNodes: [],
      },
      {
        associate: {
          associateId: 86111,
          legacyAssociateId: 319822,
          firstName: 'Misty',
          lastName: 'Rivera',
          profileUrl: null,
          associateType: 'RETAIL',
          associateStatus: 'TERMINATED',
        },
        rank: {
          rankId: 1,
          rankName: 'Ambassador',
        },
        pv: 0,
        qoV: 0,
        pa: 0,
        childTreeNodes: [],
      },
      {
        associate: {
          associateId: 86478,
          legacyAssociateId: 321223,
          firstName: 'Brooke',
          lastName: 'Mutapcic',
          profileUrl: null,
          associateType: 'PREFERRED',
          associateStatus: 'TERMINATED',
        },
        rank: {
          rankId: 1,
          rankName: 'Ambassador',
        },
        pv: 0,
        qoV: 0,
        pa: 0,
        childTreeNodes: [],
      },
      {
        associate: {
          associateId: 86556,
          legacyAssociateId: 321520,
          firstName: 'Jennifer',
          lastName: 'Hardcastle',
          profileUrl: null,
          associateType: 'PREFERRED',
          associateStatus: 'TERMINATED',
        },
        rank: {
          rankId: 1,
          rankName: 'Ambassador',
        },
        pv: 0,
        qoV: 0,
        pa: 0,
        childTreeNodes: [],
      },
      {
        associate: {
          associateId: 87565,
          legacyAssociateId: 325588,
          firstName: 'Marissa',
          lastName: 'Kloberdanz',
          profileUrl: null,
          associateType: 'AMBASSADOR',
          associateStatus: 'ACTIVE',
        },
        rank: {
          rankId: 1,
          rankName: 'Ambassador',
        },
        pv: 0,
        qoV: 0,
        pa: 0,
        childTreeNodes: [],
      },
    ],
  },
  {
    associate: {
      associateId: 80732,
      legacyAssociateId: 296803,
      firstName: 'lisa',
      lastName: 'hancock',
      profileUrl: null,
      associateType: 'PREFERRED',
      associateStatus: 'TERMINATED',
    },
    rank: {
      rankId: 1,
      rankName: 'Ambassador',
    },
    pv: 0,
    qoV: 0,
    pa: 0,
    childTreeNodes: [],
  },
  {
    associate: {
      associateId: 81392,
      legacyAssociateId: 299536,
      firstName: 'Amber',
      lastName: 'Brown',
      profileUrl: null,
      associateType: 'PREFERRED',
      associateStatus: 'TERMINATED',
    },
    rank: {
      rankId: 1,
      rankName: 'Ambassador',
    },
    pv: 0,
    qoV: 0,
    pa: 0,
    childTreeNodes: [],
  },
];
