export const mockChildTree = [
  {
    associate: {
      associateId: 81392,
      legacyAssociateId: 299536,
      firstName: 'Amber',
      lastName: 'Brown',
      profileUrl: null,
      associateType: 'PREFERRED',
      associateStatus: 'TERMINATED',
    },
    rank: {
      rankId: 1,
      rankName: 'Ambassador',
    },
    pv: 0,
    qoV: 0,
    pa: 0,
  },
  {
    associate: {
      associateId: 81695,
      legacyAssociateId: 301048,
      firstName: 'Denise',
      lastName: 'Rathjen',
      profileUrl: null,
      associateType: 'PREFERRED',
      associateStatus: 'TERMINATED',
    },
    rank: {
      rankId: 1,
      rankName: 'Ambassador',
    },
    pv: 0,
    qoV: 0,
    pa: 0,
  },
  {
    associate: {
      associateId: 75197,
      legacyAssociateId: 272398,
      firstName: 'Karlie',
      lastName: 'Hodgen',
      profileUrl: null,
      associateType: 'AMBASSADOR',
      associateStatus: 'TERMINATED',
    },
    rank: {
      rankId: 1,
      rankName: 'Ambassador',
    },
    pv: 0,
    qoV: 0,
    pa: 0,
  },
  {
    associate: {
      associateId: 202602,
      legacyAssociateId: 742546,
      firstName: 'Matthew',
      lastName: 'Adams',
      profileUrl: null,
      associateType: 'AMBASSADOR',
      associateStatus: 'ACTIVE',
    },
    rank: {
      rankId: 1,
      rankName: 'Ambassador',
    },
    pv: 0,
    qoV: 0,
    pa: 0,
  },
  {
    associate: {
      associateId: 152996,
      legacyAssociateId: 622003,
      firstName: 'Angela',
      lastName: 'Mourlam',
      profileUrl: null,
      associateType: 'AMBASSADOR',
      associateStatus: 'SUSPENDED',
    },
    rank: {
      rankId: 1,
      rankName: 'Ambassador',
    },
    pv: 0,
    qoV: 0,
    pa: 0,
  },
  {
    associate: {
      associateId: 85981,
      legacyAssociateId: 319342,
      firstName: 'Kelsey',
      lastName: 'Bowman',
      profileUrl: null,
      associateType: 'PREFERRED',
      associateStatus: 'TERMINATED',
    },
    rank: {
      rankId: 1,
      rankName: 'Ambassador',
    },
    pv: 0,
    qoV: 0,
    pa: 0,
  },
  {
    associate: {
      associateId: 86111,
      legacyAssociateId: 319822,
      firstName: 'Misty',
      lastName: 'Rivera',
      profileUrl: null,
      associateType: 'RETAIL',
      associateStatus: 'TERMINATED',
    },
    rank: {
      rankId: 1,
      rankName: 'Ambassador',
    },
    pv: 0,
    qoV: 0,
    pa: 0,
  },
  {
    associate: {
      associateId: 86478,
      legacyAssociateId: 321223,
      firstName: 'Brooke',
      lastName: 'Mutapcic',
      profileUrl: null,
      associateType: 'PREFERRED',
      associateStatus: 'TERMINATED',
    },
    rank: {
      rankId: 1,
      rankName: 'Ambassador',
    },
    pv: 0,
    qoV: 0,
    pa: 0,
  },
  {
    associate: {
      associateId: 86556,
      legacyAssociateId: 321520,
      firstName: 'Jennifer',
      lastName: 'Hardcastle',
      profileUrl: null,
      associateType: 'PREFERRED',
      associateStatus: 'TERMINATED',
    },
    rank: {
      rankId: 1,
      rankName: 'Ambassador',
    },
    pv: 0,
    qoV: 0,
    pa: 0,
  },
  {
    associate: {
      associateId: 87565,
      legacyAssociateId: 325588,
      firstName: 'Marissa',
      lastName: 'Kloberdanz',
      profileUrl: null,
      associateType: 'PREFERRED',
      associateStatus: 'TERMINATED',
    },
    rank: {
      rankId: 1,
      rankName: 'Ambassador',
    },
    pv: 0,
    qoV: 0,
    pa: 0,
  },
  {
    associate: {
      associateId: 93131,
      legacyAssociateId: 353080,
      firstName: 'Gerald',
      lastName: 'Wiederien',
      profileUrl: null,
      associateType: 'PREFERRED',
      associateStatus: 'TERMINATED',
    },
    rank: {
      rankId: 1,
      rankName: 'Ambassador',
    },
    pv: 0,
    qoV: 0,
    pa: 0,
  },
  {
    associate: {
      associateId: 93133,
      legacyAssociateId: 353092,
      firstName: 'Michelle',
      lastName: 'Bartusek',
      profileUrl: null,
      associateType: 'PREFERRED',
      associateStatus: 'TERMINATED',
    },
    rank: {
      rankId: 1,
      rankName: 'Ambassador',
    },
    pv: 0,
    qoV: 0,
    pa: 0,
  },
];
